import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * Merges Tailwind classes safely.
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/**
 * Unwraps a value that might be a plain string or an object with a
 * "value" key (as sometimes generated by AI following propsSchema).
 */
export function unwrapText(item: unknown): string {
  if (typeof item === "string") return item;
  if (item && typeof item === "object" && "value" in item) {
    return String((item as Record<string, unknown>).value ?? "");
  }
  if (item === null || item === undefined) return "";
  return String(item);
}

/**
 * Normalizes an array that may contain plain strings or {id, value} objects.
 */
export function unwrapTextArray(arr: unknown): string[] {
  if (!Array.isArray(arr)) {
    if (typeof arr === "string") return [arr];
    return [];
  }
  return arr.map(unwrapText).filter(Boolean);
}

/**
 * Normalizes various legacy formats into ContentBlock[].
 * Handles: ContentBlock[], string[], {value: string}[], or a single string.
 */
export function normalizeContentBlocks(
  raw: unknown,
): { id: string; type: "paragraph" | "bulletList" | "numberedList"; content: string }[] {
  if (!raw) return [];

  if (typeof raw === "string") {
    return [{ id: crypto.randomUUID(), type: "paragraph", content: raw }];
  }

  if (!Array.isArray(raw)) return [];

  return raw
    .map((item) => {
      if (
        item &&
        typeof item === "object" &&
        "type" in item &&
        "content" in item &&
        typeof item.content === "string"
      ) {
        return item as { id: string; type: "paragraph" | "bulletList" | "numberedList"; content: string };
      }
      const text = unwrapText(item);
      if (!text) return null;
      return { id: crypto.randomUUID(), type: "paragraph" as const, content: text };
    })
    .filter(Boolean) as { id: string; type: "paragraph" | "bulletList" | "numberedList"; content: string }[];
}
